### ISSUE TITLE
Leer y teclear el código corrigiendo los errores de dedo que trae en el libro

### ISSUE THREAD

**Issue by juliowaissman** [Topicos-IA-UNISON-2016a/SE#1]

**Comment by robbiehub** [comment]
Profe, no pude crear la branch así que por el momento subí el código a un fork:
https://github.com/robbiehub/SE

**Comment by juliowaissman** [comment]
Ya se tecleo lo básico del código por Robbie, ahora falta para completar el Issue

1. Probar que todas las funciones programadas funcionen correctamente para recommendations.py.   Esto se puede hacer creando un archivo de unidad de prueba (lo veremos) o en el main, poner varias pruebas. Es muy importante que se pueda verificar que efectivamente el código hace lo que se dice que hace.

2. ¿Como teclear el deliciusrec.py, si me parece que pydelicious ya no se encuentra en activo y funcionando ¿Instalaste el modulo? ¿Probaste tu código? Creo que delicious ya no es una opción para probar con sistemas de recomendación, así que tendremos que buscar una alternativa.

**Comment by juliowaissman** [comment]
Listo, ya tenemos el código y una unittest simple.
